### ISSUE TITLE
Major changes and new name

### ISSUE THREAD

**Issue by wotnak** [wotnak/Rby#1]
Generally, I really like the premise of the original MoreFish plugin: fun automatic event (fishing competitions) for players, however I'd like it to be more configurable and extendable.
So to achieve this I will be working on a major refactor and redesign of the original plugin and then release it under a new name.
Main goals I will be working towards are:
- more configuration options  
  *allow server administrators to fully customize fishing competition experience for their players*
- convenient api
  *allow other plugins to extend plugin functionality, mainly add new conditions and effects but also programmatically manage fish types and competitions*

__Until full release I'll  also maintain the current version of MoreFish with updates to new mc versions and bugfixes.__

## Roadmap:

- [ ] new configuration system #5 
	- [ ] fish types #6 
	- [ ] fishing competitions
- [ ] api to register new conditions and effects
- [ ] basic conditions
- [ ] basic effects
- [ ] new default fish types and competition
- [x] choose new name #2
- [ ] update checker
- [ ] documentation
- [ ] __release plugin under new name__

## Future plans:
- config packs  
  *They will allow to easily share preconfigured fish types and competitions.*
- integrations with other plugins (mainly new effects and conditions)  
  *API will provide the ability for other plugins to add new effects and conditions but support for popular ones should be included in the main plugin.*
- in game gui to manage fish types and competitions #8
