### ISSUE TITLE
Check if shop works properly 

### ISSUE THREAD

**Issue by wotnak** [wotnak/Rby#12]
There are some reports of various issues regarding shop functionality (`/mf shop`).
We should investigate if the issues still exists in the latest plugin version and provide fixes if necessary.

## Reported issues: 
- [ ] shop not recognizing fish items https://github.com/woodyn1002/more-fish/issues/41
- [ ] negative sell price https://github.com/woodyn1002/more-fish/issues/36
- [ ] shop is destroying not fish items instead of returning them to player's inventory https://github.com/woodyn1002/more-fish/issues/35
